### ISSUE TITLE
repoutil --add argument order problem

### ISSUE THREAD

**Issue by mstarostik** [MScottBlake/docker-reposado#5]
The order of arguments to repoutil --add et al. is a little unlucky with BRANCH_NAME coming last. If it was the first argument, one could easily use xargs to add a bunch of products to a branch in one go.
Surely it would break any script out there to just reverse the logic, but maybe it could be added as an alternative along the lines of the -t argument to GNU cp, mv etc.

**Comment by MScottBlake** [comment]
Please open this as an issue in the Reposado repository (https://github.com/wdas/reposado) directly. This repo makes it available in a docker container; I don't control the underlying code.

**Comment by mstarostik** [comment]
That was my intention of course m(
Sorry for the noise.
